### ISSUE TITLE
src.jpg

### ISSUE THREAD

**Issue by BackMountainDevil** [fawdlstty/FawCourse_FFmpeg#2]
老哥，你写的太棒了，就是这个github无法加载显示你的图片？？。。。。是最近github封闭端口了吗。。。我查了一下最近微博封了不少图床

**Comment by fawdlstty** [comment]
需要的话留邮箱，我私发你

**Comment by BackMountainDevil** [comment]
我的邮箱：kearneyyback@gmail.com

最近开始学习FFmpeg、希望以后学会了能帮到你更新文档。打算造一个国产开源potplayer

**Comment by fawdlstty** [comment]
你加油

**Comment by fawdlstty** [comment]
收件人邮件地址（kearneyyback@gmail.com）不存在，邮件无法送达。
host alt1.gmail-smtp-in.l.google.com[108.177.9.26] said: 550 5.1.1 https://support.google.com/mail/?p=NoSuchUser t5si2162097otm.321 - gsmtp (in reply to RCPT TO command)

**Comment by BackMountainDevil** [comment]
十分抱歉，一不小心打错了
kearneyback@gmail.com

**Comment by fawdlstty** [comment]
您的邮件被收件人（kearneyback@gmail.com）所在服务商判为垃圾邮件，对方不予接收。
host alt1.gmail-smtp-in.l.google.com[108.177.9.27] said: 552 5.7.0 message content and attachment content guidelines. z24si2300351otp.159 - gsmtp (in reply to end of DATA command)

**Comment by BackMountainDevil** [comment]
对不起，我傻了。。。我两说的是同一门语言。。。。。
191615342@qq.com
