### ISSUE TITLE
vcpkg安装ffmpeg的命令

### ISSUE THREAD

**Issue by zchrissirhcz** [fawdlstty/FawCourse_FFmpeg#6]
按这里的说明 https://github.com/fawdlstty/FawCourse_FFmpeg/blob/master/docs/03_ffmpeg_beginning.md#%E9%85%8D%E7%BD%AE%E7%8E%AF%E5%A2%83

```batch
vcpkg install ffmpeg*:x86-windows ffmpeg*:x86-windows-static
```

执行失败

看起来应该是用如下这句
```
vcpkg install ffmpeg:x86-windows ffmpeg:x86-windows-static
```

**Comment by fawdlstty** [comment]
感谢指出。这个命令以前在vcpkg里面可用，意思是安装ffmpeg时同时附带所有的feature，现在安装得
`vcpkg install ffmpeg[xxx,xxx,xxx,xxx]::x86-windows-static`
具体可用feature通过`vcpkg search ffmpeg`获取
