### ISSUE TITLE
在Windows10系统里，如何使用XAudio2来播放FFmpeg解码的数据？

### ISSUE THREAD

**Issue by ChinaChenMingQuan** [fawdlstty/FawCourse_FFmpeg#7]
理论上来说，waveOut系统函数能播放的，XAudio2也应该能才对呀。

但是我照教程来解码音频，最终结果播放的数据有部分电流声，但我完全不知道哪一步错了？

**Comment by fawdlstty** [comment]
解出PCM数据，存文件，用Audacity播放，看音频本身是否正确

**Comment by ChinaChenMingQuan** [comment]
你说的Audacity这个软件里只有Windows DirectSound，MME，Windows  WASAPI，根本没有XAudio2的测试。

我也按照你说的测试，Audacity播放都是正常的，到了XAudio2就变成了恐怖的电流声，我真*了狗了。

**Comment by ChinaChenMingQuan** [comment]
哎呀，有时候真是越新的东西越不好用。

**Comment by ChinaChenMingQuan** [comment]
老哥你能考虑下写个XAudio2的示例吗？

我是看你的教程，和微软照官方XAudio2的使用例子来写的，但就是一股莫名奇妙的电流声，心力憔悴ing。

WAVEFORMATEX这个结构体的参数明明对准的了呀，真是没道理。。。

**Comment by ChinaChenMingQuan** [comment]
。。。忘@了。

我想了个曲线救国的办法，暴力多进程。呼叫ffmpeg.exe把音频多媒体都转成wav格式，视频都转成avi格式。然后再读取到主进程吧。

@fawdlstty，大哥，我加班去了，求求你考虑下吧。。。

**Comment by ChinaChenMingQuan** [comment]
@fawdlstty，对比了我的多进程版本和你的教程解码版本，原来我死在了一个参数上。。。

WAVEFORMATEX::nAvgBytesPerSec 这个参数不一样。。。

你教程的WAVEFORMATEX::nAvgBytesPerSec的效果是恐怖电流。
我多进程的WAVEFORMATEX::nAvgBytesPerSec是正确的数值。

我能说粗口吗？

**Comment by fawdlstty** [comment]
sorry，这儿是有个坑，已修复，晚上提交gitbook。

**Comment by fawdlstty** [comment]
这个文档是我读雷总博客学到的东西，雷总只讲原理不讲用法，使得我之前踩的坑更多。ffmpeg相关资料也少，没什么可参考的，这篇文档难免有些不正确的地方，理解下咯:smile:
